### Introduction

```{r}
title: "workingwithdata"
format: html
```

```{r}
library(tidyverse)
library(haven)
library(descr)
library(haven)
library(labelled)
```

### ✅Data Management

### Sort of data

```{r}
file_path<-file.path("..","data","data.sav") 
df<-read_sav(file_path)
head(df)

```

### ✅Frequency Tables

### End of career challenges

```{r}
freq(as.ordered(df$CDCHPHYS), plot=FALSE)
```

### Stopped Dancing for New Career

```{r}
freq(as.ordered(df$DSNEWCRR) , plot=FALSE)
```

### **Ethnic Origin**

```{r}
freq(as.ordered(df$A5AETHN1) , plot=FALSE)
```

### ✅Univariate Data Visualizations

### Figure 1 Bar Graph

```{r}
#Univariate Graph (categorical variable)
df %>%
  ggplot(aes(x = DSNEWCRR)) + geom_bar()+
  ggtitle("Career Transition")

```

### Bar Graph (Var2)

```{r}
#Univariate Graph (categorical variable)
df %>%
  ggplot(aes(x = A5AETHN1)) + geom_bar()+
  ggtitle("Ethnic Origin")
```

### Bar Graph (3)

```{r}
#Univariate Graph (categorical variable)
df %>%
  ggplot(aes(x =CDCHPHYS )) + geom_bar()+
  ggtitle("End of career")
```

### Career Transition

```{r}
#Univariate Graph (categorical variable)
df %>%
  ggplot(aes(x = DSNEWCRR)) + geom_bar()+
  ggtitle("Career Transition") + 
  xlab("Stop Dancing because of New Career") +
  ylab("Count of People") +
  theme_apa() #from papaja package

```

```{r}
df %>%
  ggplot(aes(x = CDCHPHYS)) +
  geom_bar(binwidth = 5, fill = "lightblue", color = "black") +  # Adds binwidth for better visualization
  ggtitle("End of Career") +
  xlab("End Career") +
  ylab("Count of Individuals") +
  theme_minimal()
```

```{r}
df %>%
  ggplot(aes(x = DSNEWCRR)) +
  geom_bar(binwidth = 5, fill = "lightblue", color = "black") +  # Adds binwidth for better visualization
  ggtitle("Stopped Dancing") +
  xlab("Not dancing") +
  ylab("Count of Individuals") +
  theme_minimal()
```

### ✅Bivariate

### Figure 1 Histogram

```{r}
# univariate graph ( categorial variable)
df%>%
  filter(!is.na(DSNEWCRR)) %>%
  ggplot(aes(x=DSNEWCRR))+
  geom_bar()+
  ggtitle("career transition") +
  facet_wrap(~CDCHPHYS)

```

```{r}
#univariate graph (categorical variable)
df %>%
  ggplot(aes(x=DSNEWCRR)) +
  barplot(binwidth = 5,fill ="lightblue", color = "black") +
  ggtitle("Career Transition") +
  theme_apa()
```

### ✅ Bar Graph

```{r}
  ggplot(df) +
  stat_summary(aes(x=CDCHPHYS, 
                   y=DSNEWCRR),
               fun.y=mean, 
               geom="bar")+
  ggtitle("Career Transition")
```

### Bar Graph #2

```{r}
ggplot(data=df) +
  stat_summary(aes(x=CDCHPHYS,
                   y=DSNEWCRR), 
               fun.y=mean, 
               geom="bar")

```

### BoxPlots 

```{r}
## boxplots
ggplot(data=df) +
  geom_boxplot(aes(x=CDCHPHYS,
                   y=DSNEWCRR)) + 
  ggtitle("Career Transition")
```

### Density Plots 

```{r}
## density plots
ggplot(data=df) +
  geom_density(aes(x=CDCHPHYS,
                   color=DSNEWCRR)) + 
  ggtitle("Career Transition")

```

```{r}
# ==== quantitative explanatory, quantitative response ====
ggplot(data=df) +
  geom_point(aes(x=CDCHPHYS, 
                 y=DSNEWCRR)) +
  geom_smooth(aes(x=CDCHPHYS, 
                  y=DSNEWCRR), 
              method="lm")
```

### 3 Variable graph 

```{r}
ggplot(data=df) +
  geom_point(aes(x=CDCHPHYS, 
                 y=DSNEWCRR,
                 color=A5AETHN1)) +
  geom_smooth(aes(x=CDCHPHYS, 
                  y=DSNEWCRR,
                  color=A5AETHN1), 
              method="lm")
```

```{r}
# ==== categorical explanatory, categorical response, categorical 3rd variable ====
tab1 <- ftable(df$CDCHPHYS,
               df$DSNEWCRR,
               df$A5AETHN1)
tab1
tab1_colProp <- prop.table(tab1, 2)
tab1_colProp

```

```{r}
# ==== categorical explanatory, quantitative response, categorical 3rd variable ====
ftable(by(df$CDCHPHYS,
          list(df$DSNEWCRR, 
               df$A5AETHN1),
          mean, na.rm = TRUE))

```
